### ISSUE TITLE
"Suggest" example in docs does not work

### ISSUE THREAD

**Issue by beechnut** [censusreporter/census-api#22]
The docs on 'suggest' include a non-functional example. The snippet

```
http://api.censusreporter.org/1.0/table/suggest?q=pover
```

results in:

![screen shot 2014-08-18 at 11 40 44 am](https://cloud.githubusercontent.com/assets/1887182/3953647/0d3fcafc-26ee-11e4-8d01-c5d2be22f08d.png)

**Comment by JoeGermuska** [comment]
@iandees what does it take to rebuild the index? I see a script for TIGER data but not for table  data.

**Comment by JoeGermuska** [comment]
We no longer use ElasticSearch, so this is obsolete.
