### ISSUE TITLE
Geo Elastic Search

### ISSUE THREAD

**Issue by dwillis** [censusreporter/census-api#27]
When using the [Geo Elastic Search API](https://github.com/censusreporter/census-api/blob/master/API.md#get-10geoelasticsearch) I've found that it typically returns better results when the place name is in lower case. Putting some cities (Savannah, GA, for example) in proper case in the URL produces different results from using lower case:

[title case](http://api.censusreporter.org/1.0/geo/elasticsearch?q=Savannah+GA)
[lower case](http://api.censusreporter.org/1.0/geo/elasticsearch?q=savannah+ga)

Just something to note for the docs, I think.

**Comment by iandees** [comment]
Huh, that is curious. I'll lowercase the text that goes into Elastic Search just so we're consistent.

**Comment by iandees** [comment]
Fixed in d091b119a.
