### ISSUE TITLE
/data/show/ doesn't honor release when testing geoid count

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/census-api#29]
```sql
census=> select count(*) from acs2013_3yr.geoheader where sumlevel = 160;
 count 
-------
  2185
```
response for http://api.censusreporter.org/1.0/data/show/acs2013_3yr?table_ids=B01003&geo_ids=160|01000US:

```json
{  "error": "You requested 29509 geoids. The maximum is 3500. Please contact us for bulk data." }
```
That's the number of places in the 5 year.

**Comment by iandees** [comment]
This should be fixed. It might be worth testing to make sure that the `/data/show/latest` calls still work as expected.

**Comment by JoeGermuska** [comment]
Verified: http://api.censusreporter.org/1.0/data/show/latest?table_ids=B01003&geo_ids=160%7C01000US gives the error that 29,509 is too many geoids.

**Comment by iandees** [comment]
That's kind of an esoteric/non-obvious "feature" of our API that we should document somehow.

"When requesting data from the `latest` ACS release, the API will prioritize retrieving all requested geoids, rather than picking the most recent/smallest ACS release."

Does that sound right?

**Comment by JoeGermuska** [comment]
yes, good point. Maybe the error message should also suggest trying a different release?

**Comment by JoeGermuska** [comment]
but, if we make that suggestion, we run into the problem that a containment geoid selects all geoids ever, so there's no way to get the data which started this line -- even if it honors the explicit ACS, it then warns that there are some geoids which aren't in that release. I think this is essentially the same as censusreporter/censusreporter#110
