### ISSUE TITLE
API examples from code failing in production

### ISSUE THREAD

**Issue by rossettistone** [censusreporter/census-api#36]
I'm trying to pull census data using the `/geo/elasticsearch` API endpoint, but running into trouble (specifically `{"error": "'NoneType' object is not callable"}`). To make sure I was doing things right, I copied in the exact example queries from `api.py`, and found that that both returned the same error.

The examples I tried were the following: 
`http://api.censusreporter.org/1.0/geo/elasticsearch?q=new+york+city`
`http://api.censusreporter.org/1.0/geo/elasticsearch?q=chicago,+il`

I'm a bit stumped. Could the endpoint be broken, or have these examples fallen out of date?

**Comment by iandees** [comment]
The ElasticSearch index that backs these endpoints has been broken for a couple months and I haven't had a chance to re-create it. Since those endpoints aren't documented, I haven't prioritized it.

What are you using this endpoint for that the non-elasticsearch endpoint doesn't work for you? e.g. `http://api.censusreporter.org/1.0/geo/search?q=new+york+city` and `http://api.censusreporter.org/1.0/geo/search?q=chicago,+il`

**Comment by rossettistone** [comment]
I'm working on a project (https://github.com/codeforamerica/resident-web-use-research) that has existing queries to this endpoint of that look like `/geo/elasticsearch?size=1&sumlevs=160&q=oakland`. I confess this is my first day looking at the codebase (I'm resurrecting it), so I'm a little short on context for that query, as I haven't seen the project up and running yet (this issue is a blocker).

But is there perhaps an easy way to translate `/geo/elasticsearch?size=1&sumlevs=160&q=oakland` into the documented `/1.0/geo/tiger2013/tiles/<sumlevel>/<zoom>/<x>/<y>.geojson` format? I'm not really certain how to use the `x` and `y` args, or if this endpoint returns the same data format that the other one would.

**Comment by iandees** [comment]
You can replace `/geo/elasticsearch` with `/geo/search` and get somewhere. It'll accept the same args I think.

**Comment by iandees** [comment]
Looks like you'll want to replace `acs2013_5yr` with `acs2014_5yr` in that `census_reporter.js` file, too. To make it a bit more future-proof you can replace `acs2013_5yr` with `latest` and the Census Reporter API will pick the best release for you automatically.

**Comment by rossettistone** [comment]
Thank you! Those are wonderful tips, and seem to have gotten me to some kind of working state. I'll have to keep poking around to figure out where I go from here, but I'm unblocked and grateful for it :-)

**Comment by iandees** [comment]
Great! Glad it worked. I'm going to close this, but feel free to reopen and ask more questions if you have them.
