### ISSUE TITLE
Support SSL on embed.censusreporter.org

### ISSUE THREAD

**Issue by iandees** [censusreporter/census-api#39]
e.g. https://censusreporter.org/profiles/16000US0644000-los-angeles-ca/ tries to load geo tiles from `http://embed.censusreporter.org/...` and fails because they're not secure (but the origin is). Let's add SSL there.

**Comment by iandees** [comment]
This is done via CloudFront custom SSL now.

**Comment by ryanpitts** [comment]
ooh nice!

**Comment by iandees** [comment]
Lack of SSL on embed.censusreporter.org was causing tile problems in https://github.com/censusreporter/census-api/issues/54, too. Yay fixed!
