### ISSUE TITLE
Improve place and table search

### ISSUE THREAD

**Issue by iandees** [censusreporter/census-api#43]
Go back to using full text search (via Elasticsearch or Postgres).

Here are some ideas for place searches and the expected outputs:
- `new york` should include New York City (the place)
- `spokane schools` should include 97000US5308250 (Spokane Public Schools)

**Comment by Joonpark13** [comment]
@tuchandra and I are currently working on this on the full-text-search branch using postgres. Currently we're looking at tables only and starting out by incorporating table title, subject area, column titles, and universe (weighted from highest to lowest, respectively).

**Comment by iandees** [comment]
Thanks for the update, @Joonpark13!

**Comment by tuchandra** [comment]
This has been implemented in the pull request for `full-text-search`, #46. 

In our version of the search in the `full-text-search` branch, both queries now have the behavior as described (tested just now).

**Comment by JoeGermuska** [comment]
Both of these examples work in the public interface as described. This was just overlooked to close.
