### ISSUE TITLE
Places without maps

### ISSUE THREAD

**Issue by tuchandra** [censusreporter/census-api#47]
Places that have sumlevels without maps do not appear in search results, but they do have automatically generated profile pages.

There are three sumlevels for which maps do not exist: 355 (NECTA Divisions), 067 (subbarrios), and 258 (Tribal Block Groups). We can see this by looking at a table that @Joonpark13 have created with metadata about profiles and tables. In this table text2 is sumlevel, and text3 is sumlevel name.

```
census=# select text2, count(*) from search_metadata where text3 is null group by text2;
 text2 | count 
-------+-------
 355   |    10
 067   |   145
 258   |   915
(3 rows)
```

The sumlevel names are populated by a series of update statements, all of which can be viewed in `full-text-search/metadata_script.sql` (on the branch `full-text-search`). These update statements are in turn taken from `census_extractomatic/api.py`, which has a dictionary at the top mapping sumlevels to names:

```
SUMLEV_NAMES = {
    "010": {"name": "nation", "plural": ""},
    "020": {"name": "region", "plural": "regions"},
    "030": {"name": "division", "plural": "divisions"},
    ...
```

Notably, the three sumlevels listed above are absent from this dictionary. 

These pages are excluded from search results. An API call to `api.censusreporter.org/1.0/geo/search?q=puerto r` returns six results, one of which is the place "Puerto Real Subbarrio." But the same search from the Census Reporter home page does not include this place in the autocomplete suggestions.

Puerto Real Subbarrio still has an automatically generated [profile page](https://censusreporter.org/profiles/06700US720532800765610-puerto-real-subbarrio/) with meaningful data. [Other](http://censusreporter.org/profiles/06700US721276472985737-venezuela-subbarrio/) [such](http://censusreporter.org/profiles/35500US7165072104-brockton-bridgewater-easton-ma-necta-division/) [pages](http://censusreporter.org/profiles/25800US2430T00300B-tribal-block-group-b/) also exist, having pages with data but no map. See the queries at the bottom for more examples of such places.

The maps on in these pages' headers are all world maps.

A resolution to this issue will involve a design decision on what to do with these places (should they appear in search results? should they have profile pages?), and the implementation of this decision.

```
census=# select display_name, full_geoid from tiger2014.census_name_lookup where sumlevel = '067';
        display_name        |       full_geoid       
----------------------------+------------------------
 Valencia subbarrio         | 06700US721278407984771
 Melilla subbarrio          | 06700US721277969352900
 Pueblo Norte subbarrio     | 06700US720230981864776
 Pueblo Sud subbarrio       | 06700US720230981865005
 Pueblo Nuevo subbarrio     | 06700US720230981864819
...


census=# select display_name, full_geoid from tiger2014.census_name_lookup where sumlevel = '355';
                       display_name                        |    full_geoid     
-----------------------------------------------------------+-------------------
 Boston-Cambridge-Newton, MA NECTA Division                | 35500US7165071654
 Brockton-Bridgewater-Easton, MA NECTA Division            | 35500US7165072104
 Framingham, MA NECTA Division                             | 35500US7165073104
 Haverhill-Newburyport-Amesbury Town, MA-NH NECTA Division | 35500US7165073604
 Lawrence-Methuen Town-Salem, MA-NH NECTA Division         | 35500US7165074204
 Lowell-Billerica-Chelmsford, MA-NH NECTA Division         | 35500US7165074804
 Lynn-Saugus-Marblehead, MA NECTA Division                 | 35500US7165074854
 Nashua, NH-MA NECTA Division                              | 35500US7165075404
 Peabody-Salem-Beverly, MA NECTA Division                  | 35500US7165076524
 Taunton-Middleborough-Norton, MA NECTA Division           | 35500US7165078254
(10 rows)

census=# select display_name, full_geoid from tiger2014.census_name_lookup where sumlevel = '258' limit 15;
     display_name     |     full_geoid     
----------------------+--------------------
 Tribal Block Group A | 25800US1185T00100A
 Tribal Block Group B | 25800US1185T00100B
 Tribal Block Group C | 25800US1185T00100C
 Tribal Block Group A | 25800US2430T03500A
...
```

**Comment by JoeGermuska** [comment]
This is a non-issue as a result of this SQL clause https://github.com/censusreporter/census-api/blob/master/full-text-search/metadata_script.sql/#L34
