### ISSUE TITLE
Bulk data access

### ISSUE THREAD

**Issue by maxogden** [censusreporter/census-api#59]
Hiya! Over at the Dat project we wanna feature the Census Reporter data as an example dataset. The goal is we could have all of your data exposed as a bulk data feed that analysts could easily pull into different research workflows. 

I was wondering if you offer any sort of bulk data endpoint, such as how CA Civic Data has their bulk download ZIPs http://calaccess.californiacivicdata.org/downloads/latest/ that we can use to create a version controlled history of their whole archive.

We could also potentially do it through [your API](https://github.com/censusreporter/census-api/blob/master/API.md), but I don't see a way through the current API to get a changes feed we could subscribe to.

**Comment by iandees** [comment]
Hi Max! I'm happy to hear that Dat is interested in this.

Since we only get data from the Census twice a year, we haven't considered adding the concept of a change feed.

I could see dumping a CSV with all the rows and columns from the American Community Survey (our backing dataset). It would probably look a lot like the SQL dumps we have available here: http://censusreporter.tumblr.com/post/73727555158/easier-access-to-acs-data. Would that work for your usecase?

**Comment by maxogden** [comment]
@iandees oh cool, those SQL files look great actually, don't worry about converting to CSV. Is there any additional cleaning of the data you do between those SQL files and what is served through the API?

**Comment by iandees** [comment]
Nope the SQL comes straight from the database that backs the API.

**Comment by maxogden** [comment]
@iandees excellent, one last question, would downloading the 2015 5 year data contain the equivalent information as downloading the 2011, 2012, 2013, 2014 and 2015 1 year data?

**Comment by maxogden** [comment]
weeeeeee
<img width="575" alt="screen shot 2017-01-15 at 2 27 55 pm" src="https://cloud.githubusercontent.com/assets/39759/21966779/dd154562-db2e-11e6-8919-447c0ef64205.png">

**Comment by iandees** [comment]
Amazon thanks you 😄 .

The 1 year releases cover different geographies and have some different columns than the 5 year releases. 1 year releases only contain data from the previous year's survey results so they are the most recent but only cover geographies with more than 65,000 population. The 5 year release  cover the previous 5 years of survey results so it covers all geographies. Each year the survey changes a tiny bit so subsequent data releases can't always be compared.

You can read more about the release schedule [in our glossary](https://censusreporter.org/glossary/) and on the [Census "Which Release Should I Use" page](http://www.census.gov/programs-surveys/acs/guidance/estimates.html).

**Comment by JoeGermuska** [comment]
Looks like we can close this...
