### ISSUE TITLE
get-10georeleasegeoidparents API example/endpoint broken

### ISSUE THREAD

**Issue by aok1425** [censusreporter/census-api#60]
[This example](https://github.com/censusreporter/census-api/blob/master/API.md#get-10georeleasegeoidparents):
`$ curl "http://api.censusreporter.org/1.0/geo/tiger2013/04000US55/parents"`
returns 301: permanently removed.

thanks for your product--it's great!

**Comment by JoeGermuska** [comment]
Thanks for the pointer.  FYI, it should be https://api.censusreporter.org/1.0/geo/tiger2015/04000US55/parents

@iandees do you think we should come up with a URL that replaces/supplements the release-specific `tiger2015` with something symbolic, like `latest` ?
