### ISSUE TITLE
Issue with data retrieval from API 

### ISSUE THREAD

**Issue by jdgodchaux** [censusreporter/census-api#66]
When I `curl` the [example](https://github.com/censusreporter/census-api/blob/master/API.md#data-retrieval) in the Census Reporter API documentation I get the following response:

```
$ curl "https://api.censusreporter.org/1.0/data/show/latest?table_ids=B13016&geo_ids=04000US55"
{"error": "The ACS 2015 5-year release doesn't include GeoID(s) 04000US55."}
```

Am I doing something wrong or is there an issue with the API? Thanks!

**Comment by iandees** [comment]
I'm in the middle of adding 2016 5-year data. This shouldn't have broken requests like this, but it looks like people are having problems. It should be fixed in the next day or so when I finish adding the new data. I'll update here when it is fixed.

**Comment by iandees** [comment]
This should be back to working. Let me know if you're still seeing problems.

**Comment by jdgodchaux** [comment]
Looks good! Thank you!
