### ISSUE TITLE
Tables B992704 and B992705 Return same value

### ISSUE THREAD

**Issue by jboyda** [censusreporter/census-api#69]
Calling B992704 and B992705 returns the same value for "Total".

I struggle to believe its a coincidence for every geoID considered B992704 is employer provided healthcare and B992705 is self purchased healthcare

**Comment by JoeGermuska** [comment]
The "total" column in an ACS table is the total number of people in the universe for that table. The universe is the same for those two tables, so the total should be the same.

Also, please be aware that tables with numbers beginning with 99 are technical tables giving information about how the survey was conducted. They should not be understood to reflect actual estimates about the number of people who had one kind of health care or the other.

See https://www.census.gov/programs-surveys/acs/methodology/sample-size-and-data-quality/item-allocation-rates-definitions.html for more about allocation.
