### ISSUE TITLE
Previous years of ACS data still supported?

### ISSUE THREAD

**Issue by jdgodchaux** [censusreporter/census-api#70]
Hello!

When I curl for previous years of ACS data, I'm getting a not found error like the following:

```
curl "https://api.censusreporter.org/1.0/data/show/acs2015_5yr?table_ids=B01001&geo_ids=16000US5367000"
...
<h1>Not Found</h1>
<p>The acs2015_5yr release isn't supported.</p>
```

Are the previous years data no longer available or am I incorrectly trying to access them?

Thank you for this amazing tool!

**Comment by iandees** [comment]
Hello! You're right, the older releases aren't available because we don't have the budget to keep them in the database.

To have access to the data you can download past releases as PostgreSQL dumps here: http://censusreporter.tumblr.com/post/73727555158/easier-access-to-acs-data

**Comment by jdgodchaux** [comment]
Bummer! Thank you Ian for following up and pointing out the PostgreSQL dumps of past releases!
