### ISSUE TITLE
Document geometry types 

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/census-api#76]
Rather than merging #68 we've decided to update the API documentation to make it clear that we return geometry as it comes from TIGER, so queries may include a mix of `Polygon` and `MultiPolygon` results.

**Comment by charlesreid1** [comment]
PR #68 does precisely that - it updates the documentation to reflect that queries can return `Polygon` results and not just `MultiPolygon` results.

**Comment by JoeGermuska** [comment]
closing in favor of #68
