### ISSUE TITLE
Census Reporter API rate limiting

### ISSUE THREAD

**Issue by gdavoian** [censusreporter/census-api#78]
Hi folks.

This isn't really an issue, it's actually a question.

Does https://api.censusreporter.org/ have any rate-limiting mechanisms?

Looks like it has, but I can't find any relevant documentation.

Thank you in advance.

**Comment by iandees** [comment]
Hello! It does have rate limiting, but I tend to change the limit based on how much traffic we're getting, so I haven't documented it.

I believe the request limit right now is ~1 request per second, with a burst of 50 requests or so.

**Comment by gdavoian** [comment]
Is it the total limit or per IP address or so?

**Comment by iandees** [comment]
Yep, per IP address.
