### ISSUE TITLE
Downloading csv and geojson file for Population Density data on a "Block Group" level

### ISSUE THREAD

**Issue by armsp** [censusreporter/census-api#79]
Not really an issue, but a question as it was suggested on the [web page](https://censusreporter.org/data/table/?table=B01003&geo_ids=01000US,150|01000US&primary_geo_id=01000US) to raise an issue for bulk data download.

I am trying to get data for population density on "Block Group" level, in csv as well as GeoJson format. I selected "block groups" from page for [table B01003](https://censusreporter.org/data/table/?table=B01003&geo_ids=01000US&primary_geo_id=01000US) but the size has too many records. 

Will this dataset help me figure out population density? If yes, then how do I download it?

On the API level I tried `https://api.censusreporter.org/2.0/table/2018/B01003` and `https://api.censusreporter.org/2.0/table/latest/B01003` but I don't get what I want.

Any help on how to download the file would be really appreciated.
Will be using it for personal analysis.

**Comment by iandees** [comment]
If you're trying to do analysis across larger swaths of data than what the API supports, I would recommend grabbing the [Postgres dumps](https://censusreporter.tumblr.com/post/73727555158/easier-access-to-acs-data), loading those into a local postgres instance, and doing some querying to get the data out.
