### ISSUE TITLE
/1.0/geo/<release>/<geoid> is not working

### ISSUE THREAD

**Issue by Jhonatangiraldo** [censusreporter/census-api#88]
## Description
Hi! When trying to fetch **https://api.censusreporter.org/1.0/geo/tiger2016/04000US55** the response is
```
// 20220406190447
// https://api.censusreporter.org/1.0/geo/tiger2016/04000US55

{
  "error": "Unknown TIGER release"
}
```
I wonder what api should i use since the URL has been used for some time, and it's also referenced here in the documentation ->
https://github.com/censusreporter/census-api/blob/master/API.md#get-10georeleasegeoid

Thank you so much in advance

**Comment by iandees** [comment]
The tiger2016 release is no longer supported. Right now the only tiger release supported is tiger2020.

**Comment by Jhonatangiraldo** [comment]
gotcha, thank you for the info, could I issue a PR with the update in the readme?

**Comment by iandees** [comment]
Yep, that'd be very helpful, thanks.

**Comment by Jhonatangiraldo** [comment]
Ok, thank you for letting me help, [THIS PR](https://github.com/censusreporter/census-api/pull/89) has been opened to address this topic, will close this issue
